deploy:
  provider: heroku
  api_key:
    secure: lB3iInss4QpHWwrG5MfJwSknc9oZsxxhKNg0hwh9fFCWZh3EzpqlYydW5rKWAMgm8lvmmC32N2C98zIoRfNiFY/OQnzaJoSrORtV7uPs6XfNkknXHmCJVuiQSUx4NMXv9xDVs4HBxjDl2S6Irg8B3xSnpWVBCrdfDjFyek7eLPwu+abcPXLVjFegFwrok5e5Uxqcj3w0jZkGu3ytLqGwiiBMv5na9IhkjPR4TZ0qaaRa2NSZM/vSY0H4kwivbKEv5LUHBmHwnUfhhAS1vEX2kB+awSvxAu/tq3tq0BO6qDs/HbTU6Ll4W1aIazwNIONYlbOBd8yi2CIUeXgfK7UMNCsHSEzH8c5Kr5lGAVLazZfXL+P4dGfcD1rNJxNO6bYYEOMviyXtqsnA4ild5YL8VUwQvD0F73sH+mpE3+P1HY6/npxYDcPfhGm80CRlOuFzswWXThgPjR+HfWlat6J3wIEoYwyCSeYRx8C6qcDA9AVBQs42A1WyIvbc/bko1GfbrJXo140tfcWWu78AOH9l0dmPOHpvsh3vBpJDiRzuhuCkvRwE/EF9FT7qumyrTYKzjYiQZCV7BJGFhi5NePRcGiCa9XiBtmg0Ei2HSn50K2HGNABzw9XoM3YfGj+WQn8zpKAsD6MrtSv6t9sLf3X2sn/PO6Qj6Ia46r8p/Nv5mOY=
  app: hooshome
  skip_cleanup: true
language: python
python:
- 3.6.1
install:
- pip install -r requirements-build.txt
- pip install social-auth-app-django
script:
- python manage.py test home
